# Generated by Django 3.2.9 on 2023-03-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulickiego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostawaokulickiego',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
