# Generated by Django 3.2.9 on 2023-03-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulickiego', '0002_dostawaokulickiego_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaneStacjiOkulickiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skr_nazwa', models.CharField(max_length=100)),
                ('nazwa', models.CharField(max_length=250)),
                ('adrres', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
