# Generated by Django 3.2.9 on 2023-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulickiego', '0003_danestacjiokulickiego'),
    ]

    operations = [
        migrations.AddField(
            model_name='danestacjiokulickiego',
            name='adress_email',
            field=models.EmailField(default='slawomirwitek@watkem.pl', max_length=254),
        ),
    ]
